# Generated by Django 4.2.1 on 2023-05-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_team_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Agent',
        ),
    ]
