# Generated by Django 4.2.1 on 2023-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_team_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_features',
            field=models.BooleanField(default=False),
        ),
    ]
