# Generated by Django 4.2.1 on 2023-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_testimony_alter_agent_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='image_small',
            field=models.ImageField(default='class', upload_to='photo/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
