# Generated by Django 4.2.1 on 2023-05-14 22:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_testimony_image_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='14 May 2023')),
                ('header', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('quote', models.CharField(max_length=255)),
                ('quote_author', models.CharField(max_length=255)),
                ('facebook_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
                ('instagram_link', models.URLField(max_length=100)),
                ('linkedin_link', models.URLField(max_length=100)),
                ('is_features', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
