# Generated by Django 4.2.1 on 2023-05-16 12:35

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 16, 13, 35, 43, 906944))),
                ('header', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('quote', models.CharField(max_length=255)),
                ('quote_author', models.CharField(max_length=255)),
                ('facebook_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
                ('instagram_link', models.URLField(max_length=100)),
                ('linkedin_link', models.URLField(max_length=100)),
                ('is_features', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
