# Generated by Django 4.2.1 on 2023-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='skype',
            field=models.CharField(default='p', max_length=20),
            preserve_default=False,
        ),
    ]
