# Generated by Django 4.2.1 on 2023-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_skype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='about',
            field=models.TextField(max_length=255),
        ),
    ]
