# Generated by Django 4.2.1 on 2023-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_is_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_features',
            field=models.BooleanField(default=False),
        ),
    ]
